### ISSUE TITLE
Example is failing in the Minishift local environment

### ISSUE THREAD

**Issue by ilterpehlivan** [fabric8-quickstarts/karaf-camel-amq#37]
I did clone the latest code then mvn install , mvn fabric8:deploy
It is succesfully created image and uploaded my local environment but i see the following error in the log:

2016-09-02 20:25:04,740 | ERROR | FelixStartLevel | BlueprintCamelContext | 62 - org.apache.camel.camel-blueprint - 2.17.3 | Error occurred during starting Camel: CamelContext(jms-example-context) due Invalid broker URI: tcp://${env+service:ACTIVEMQ_SERVICE_NAME}

java.lang.IllegalArgumentException: Invalid broker URI: tcp://${env+service:ACTIVEMQ_SERVICE_NAME} 

It looks like camel cannot read the ACTIVEMQ_SERVICE_NAME. However I see it is part of the deployment.yml

There might be any bug in the code ? Instead of ${env+service:ACTIVEMQ_SERVICE_NAME} 
${env:ACTIVEMQ_SERVICE_NAME}

**Comment by dhirajsb** [comment]
@lburgazzoli can you take a look?

**Comment by lburgazzoli** [comment]
The syntax is correct and it does the follow:

- resolve the env var ACTIVEMQ_SERVICE_NAME
- retrieve the service associated with the ACTIVEMQ_SERVICE_NAME in the form of host:port using kubernetes service discovery standards

i.e. if you have an env var ACTIVEMQ_SERVICE_NAME set to ```broker```

1. ${env+service:ACTIVEMQ_SERVICE_NAME} will be resolved as ${service:broker}
2. ${service:broker} will then looks for the following env vars:
  - BROKER_SERVICE_HOST 
  - BROKER_SERVICE_PORT
3. the result would then in the form of host:port but if the previous vars are not available the entire evaluation is discarded.

So you first need to be sure that your A-MQ instance (which is required to be installed before) is properly set-up and if ACTIVEMQ_SERVICE_NAME reflects your setup.

**Comment by ilterpehlivan** [comment]
thanks for the explanation @lburgazzoli . I will try as you described
